// Matrix Addition
#include<iostream.h>
#include<conio.h>
void main()
{
	int r, c, a[100][100], b[100][100], sum[100][100], i, j;
	clrscr();
	cout<<"Enter number of rows : ";
	cin>>r;
	cout<<"Enter number of columns : ";
	cin>>c;
	cout<<"Enter elements of 1st matrix : "<<endl;
	for(i=0; i<r; ++i)
		for(j=0; j<c; ++j)
		{
			cout<<"Enter element a"<<i+1<<j+1<<" : ";
			cin>>a[i][j];
		}
	cout<<"Enter elements of 2nd matrix : "<<endl;
	for(i=0; i<r; ++i)
		for(j=0; j<c; ++j)
		{
			cout<<"Enter element b"<<i+1<<j+1<<" : ";
			cin>>b[i][j];
		}
	for(i=0; i<r; ++i)
		for(j=0; j<c; ++j)
			sum[i][j] = a[i][j] + b[i][j];
	cout<<"Sum of two matrix is : "<<endl;
	for(i=0; i<r; ++i)
		for(j=0; j<c; ++j)
		{
			cout<<sum[i][j]<<" ";
			if(j==c-1)
				cout<<endl;
		}
	getch();
}